version: '3.8'

services:
 #Services
  node:
    container_name: docker-mongodb
    image: docker-mongodb
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - '80:3000'
    environment:
      - DATABASE_URL="mongodb"://mongo:27017"
    links:
      - mongo  

  #mongodb
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:

  
     
    
